config/routes.rb
Rails.application.routes.draw do
  root to: 'users#new'
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :pictures
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def authenticate_user
    if @current_user == nil
      flash[:notice] = t('notice.login_needed')
      redirect_to new_session_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  def index
    if params[:title_key]
      @pictures = Picture.where('title LIKE ?', "%#{params[:title_key]}%")
    else
      @pictures = Picture.all
    end
  end

  def new
    if params[:back]
     @picture = Picture.new(picture_params)
    else
     @picture = Picture.new
    end
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      if @picture.save
        redirect_to pictures_path, notice: "作成しました！"
      else
        flash.now[:notice] = '作成に失敗しました'
        render :new
      end
    end
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice:"削除しました！"
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    if @picture.invalid?
      redirect_to new_picture_path, flash: { error: @picture.errors.full_messages }
    end
  end

  private
  def picture_params
    params.require(:picture).permit(:title, :content, :image, :image_cache)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id), notice: "ログインしました!"
    else
      flash.now[:notice] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
      session.delete(:user_id)
      redirect_to new_session_path, notice: "ログアウトしました!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
      @user = User.new(user_params)
      if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

    private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Selfportraitapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><%= image_tag 'app_logo.svg', width:'40px', height:'40px', alt: 'ロゴ' %></a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= image_tag 'search.svg', width:'20px', height:'20px', alt: '検索' %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li>
                    <%= form_tag('/pictures', method: 'get') do %>
                    <%= label_tag(:title_key, 'Search title:') %>
                    <%= text_field_tag(:title_key) %>
                    <%= submit_tag('Search') %> <%= link_to 'Clear', pictures_path %>
                    <% end %>
                  </li>
                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-left">
              <li class="active"><a href="#">
                <%= image_tag 'home.svg', width:'30px', height:'30px', alt: 'home' %>
                <span class="sr-only">(current)</span></a>
              </li>
              <li><a href="#" class="icon">
                <%= image_tag 'friend.svg', width:'30px', height:'30px', alt: 'friend' %></a>
              </li>
              <li><a href="#" class="icon">
                <%= image_tag 'watch.svg', width:'30px', height:'30px', alt: 'watch' %></a>
              </li>
              <li><a href="#" class="icon">
                <%= image_tag 'shop.svg', width:'30px', height:'30px', alt: 'shop' %></a>
              </li>
              <li><a href="#" class="icon">
                <%= image_tag 'group.svg', width:'30px', height:'30px', alt: 'group' %></a>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">アカウント<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <% if logged_in? %>
                  <li><%= link_to "Profile", user_path(current_user.id) %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
                  <% else %>
                  <li><%= link_to "Sign up", new_user_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Login", new_session_path %></li>
                  <% end %>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true ,url: choose_new_or_edit ) do |form| %>
<% if flash[:error].present? %>
    <ul class="errors">
      <% flash[:error].each do |e| %>
        <li><%= e %></li>
      <% end %>
    </ul>
  <% end %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="picture_title">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div class="picture_title">
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </div>
  <div class="field confirm_img">
    <%= form.label :image %><br>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <span><%= form.file_field :image %></span>
    <%= form.hidden_field :image_cache %>
  </div>
  <br>
  <%= form.submit %>
<% end %>
<br>
<%= form_with(model: @picture, url: new_picture_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>
<br>
<%= link_to "ブログ一覧画面にもどる", pictures_path %>

app/views/pictures/confirm.html.erb
<div class="fuield">
  <h3>以下の内容で、送信する。</h3>
  <%= form_with(model: @picture, local: true) do |form| %>
    <%= form.hidden_field :title %>
    <%= form.hidden_field :content %>
    <p>タイトル:<%= @picture.title %></p>
    <p>本文:<%= @picture.content %></p>
    <p class="confirm_img"><%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %></p>
    <%= form.hidden_field :image_cache %>
    <br>
    <%= form.submit "登録する" %>
  <% end %>
  <br><br>
  <%= form_with(model: @picture, url: new_picture_path, local:true, method:"get") do |form| %>
    <%= form.hidden_field :title %>
    <%= form.hidden_field :content %>
    <%= form.hidden_field :image_cache %>
    <%= form.submit "戻る", name: "back" %>
  <% end %>
  <br>
</div>

app/views/pictures/edit.html.erb
<div class="fuield">
  <h2>編集する</h2>
  <%= render 'form' %>
</div>

app/views/pictures/index.html.erb
<div class="main row">
  <div class="col-xs-0 col-sm-1 col-md-2 col-lg-3 side_category hidden-xs hidden-sm">
    <ul>
      <li>プロフィール</li>
      <li><a href="#" class="icon">
        <%= image_tag 'friend.svg', width:'30px', height:'30px', alt: 'friend' %></a>
      </li>
      <li><a href="#" class="icon">
        <%= image_tag 'watch.svg', width:'30px', height:'30px', alt: 'watch' %></a>
      </li>
      <li><a href="#" class="icon">
        <%= image_tag 'shop.svg', width:'30px', height:'30px', alt: 'shop' %></a>
      </li>
      <li><a href="#" class="icon">
        <%= image_tag 'group.svg', width:'30px', height:'30px', alt: 'group' %></a>
      </li>
    </ul>
  </div>
  <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6 main_contents">
    <h1>一覧</h1><span class="notice"><%= notice %></span>
    <%= link_to '新しく投稿する', new_picture_path, class: 'btn btn-primary' %>
    <% @pictures.each do |picture| %>
      <table>
        <tr>
          <th>投稿者：<%= picture.user.name %></th>
          <td>
            <%= link_to '詳細', picture_path(picture.id), class: 'btn btn-info' %>
            <% if picture.user_id == current_user.id %>
              <%= link_to "編集", edit_picture_path(picture.id),
              data: { confirm: '本当に編集していいですか？' }, class: 'btn btn-warning' %>
              <%= link_to '削除', picture_path(picture.id),method: :delete,
              data: { confirm: '本当に削除していいですか？' }, class: 'btn btn-danger' %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td colspan="2">タイトル：<%= picture.title %></td>
        </tr>
        <tr>
          <td colspan="2">内容：<br><%= picture.content %></td>
        </tr>
        <tr>
          <td class="picture_img" colspan="2" rowspan="2">Image<br><img src="<%= picture.image %>"</td>
        </tr>
      </table>
    <% end %>
  </div>
  <div class="col-xs-0 col-sm-1 col-md-2 col-lg-3 aside">
    <img src="/assets/koukoku.png" width="300px" height="300px" alt="広告">
    <hr>
    <img src="/assets/koukoku.png" width="300px" height="300px" alt="広告">
  </div>
</div>

app/views/pictures/new.html.erb
<div class="fuield">
  <span class="notice"><%= notice %></span>
  <h2>作成する</h2>
  <%= render 'form' %>
</div>

app/views/pictures/show.html.erb
<div class="fuield">
  <h1>詳細画面</h1>
  <p>タイトル: <%= @picture.title %></p>
  <p>内容: <%= @picture.content %></p>
  <p id="notice"><%= notice %></p>

  <p class="picture_img">Image:<br>
    <%= image_tag @picture.image.url if @picture.image && @picture.image.url %>
  </p>
  <% unless @picture.user_id == current_user.id %>
    <% if @favorite.present? %>
      <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
    <% end %>
  <% end %>
  <%= link_to "一覧画面にもどる", pictures_path, class: 'btn btn-secondary' %>
</div>

app/views/users/new.html.erb
<div class="fuield">
  <h1>アカウント登録</h1>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with(model: @user, local: true) do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <%= f.label :email %><br>
    <%= f.email_field :email %><br>
    <%= f.label :password %><br>
    <%= f.password_field :password %><br>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %><br>
    <br>
    <%= f.submit "アカウント登録" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="fuield">
  <span class="notice"><%= notice %></span>
  <h1><%= @user.name %>のページ</h1>
  <p>メールアドレス: <%= @user.email %></p>
  <% if logged_in? %>
    <%= link_to "ブログ一覧へ！", pictures_path, class: 'btn btn-info' %>
  <% else %>
    <%= link_to "ログイン", new_session_path, class: 'btn btn-info' %>
  <% end %>
</div>